### PR TITLE
Fix for presence detection

### PR DESCRIPTION
**Pull request by rowrawer**
The current implementation of presence detection doesn't work. Switched to simpler app id based detection instead

### CODE REVIEW

**Comment by rowrawer** [comment]
I've also noticed the "now playing" status disappearing often when using the 20 second delay. Maybe it's just Last.fm breaking but it might be too quick, I'm not sure.

**Comment by dimdenGD** [comment]
It never was an issue for me and I've had it set to 15 before

**Comment by rowrawer** [comment]
In that case it's probably just Last.fm having issues.

**Comment by dimdenGD** [comment]
You can just log the requests and see if they come fine or not to see if its bug in code or in last fm

**Comment by dimdenGD** [comment]
Does it work for you? I got someone else complaining it doesn't work anymore

**Comment by 54ac** [comment]
Yes, it works fine for me regardless of the options.

**Comment by dimdenGD** [comment]
image
I've got many reports that plugin doesnt work when this is enabled

**Comment by 54ac** [comment]
Works fine for me. If any other activity is detected, it sets an empty activity. The code is the same as in the Spotify option, except it looks for any activity other than itself.

**Pull request merged**
